version: '3.9'

volumes:
  management-data:

networks:
  management-tier:

services:
  postgres:
    image: amilosh/management-postgres:12.9
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: management-db
    ports:
      - 5432:5432
    volumes:
      - management-data:/var/lib/postgresql/data
    networks:
      - management-tier

  management:
    image: amilosh/management
    container_name: management
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=management-db
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - management-tier