version: '3.9'

volumes:
  postgres-volume:

services:
  db:
    image: postgres:12.9
    container_name: management-container -e
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: management-db
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data